#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

# GETTING-STARTED: change 'db.sqlite3' to your sqlite3 database:
if [ ! -f $OPENSHIFT_DATA_DIR/db.sqlite3 ]
then
    # GETTING-STARTED: change 'myproject' to your project name and 'db.sqlite3' to the name of your sqlite3 database:
    echo "Copying $OPENSHIFT_REPO_DIR/wsgi/myproject/db.sqlite3 to $OPENSHIFT_DATA_DIR"
    # GETTING-STARTED: change 'myproject' to your project name and 'db.sqlite3' to the name of your sqlite3 database:
    cp "$OPENSHIFT_REPO_DIR"wsgi/myproject/db.sqlite3 $OPENSHIFT_DATA_DIR
    python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
else
    # GETTING-STARTED: change 'myproject' to your project name:
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/myproject/manage.py syncdb --noinput'"
    # GETTING-STARTED: change 'myproject' to your project name:
    python "$OPENSHIFT_REPO_DIR"wsgi/myproject/manage.py syncdb --noinput
fi

# GETTING-STARTED: change 'myproject' to your project name:
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/myproject/manage.py collectstatic --noinput'"
# GETTING-STARTED: change 'myproject' to your project name:
python "$OPENSHIFT_REPO_DIR"wsgi/myproject/manage.py collectstatic --noinput
