# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Metric',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=200, verbose_name=b'Metric name')),
        #         ('definition', models.CharField(verbose_name=b'Definition of metric')),
        #         ('direction', models.BooleanField(default=1, verbose_name=b'Do you want this value to go up or down?')),
        #         ('historic', models.BooleanField(default=0, verbose_name=b'Is the target value based on history, or is there a manual input?')),
        #         ('target', models.FloatField(verbose_name=b'What is the target value?')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField(verbose_name=b'Input variable value.')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name=b'Date when variable value was input.')),
            ],
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='input_spec',
        #     field=models.CharField(choices=[(b'1', b'Manual'), (b'2', b'Server Upload'), (b'3', b'SQL Database')], default=b'1', max_length=1),
        # ),
        migrations.AddField(
            model_name='value',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cityscore.City'),
        ),
        # migrations.AddField(
        #     model_name='value',
        #     name='metric',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cityscore.Metric', verbose_name=b'Measured metric corresponding to value'),
        # ),
        # migrations.AddField(
        #     model_name='metric',
        #     name='city',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cityscore.City', verbose_name=b'The account to which this information belongs'),
        # ),
    ]
