# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0006_auto_20160630_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['entry_date']},
        ),
    ]
