# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0008_auto_20160630_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='definition',
            field=models.CharField(max_length=200, verbose_name=b'Definition of metric'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='direction',
            field=models.BooleanField(default=1, verbose_name=b'Check this box if an improvement in the metric is indicated by it going up (e.g., smiles). Leave it unchecked in the opposite case (e.g., frowns).'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='historic',
            field=models.BooleanField(default=0, verbose_name=b'Check the box if you have a target for this metric. If unchecked, you will not be able to generate scores for this metric without at least a year of data, at which point we will automatically calculate the target.'),
        ),
    ]
