# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0009_auto_20160630_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='target',
            field=models.FloatField(verbose_name=b'What is the target value? (Leave as 0 if the above is checked.)'),
        ),
    ]
