# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0010_auto_20160630_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='input_spec',
        ),
    ]
