# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0011_remove_city_input_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='historic',
            field=models.BooleanField(default=0, verbose_name=b'Check the box if you lack a target for this metric. If checked, you will not be able to generate scores for this metric without at least a year of data, at which point we will automatically calculate the target.'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='target',
            field=models.FloatField(verbose_name=b'What is the target value? (Leave as 1 if the above is checked.)'),
        ),
    ]
