# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityscore', '0012_auto_20160705_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='trend',
            field=models.BooleanField(default=0, verbose_name=b'Check this box if this metric is measured on a long-term basis (ex. homicides). This means that there may be days where the value is zero, for which the score is not relevant.'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='historic',
            field=models.BooleanField(default=0, verbose_name=b"Check the box if you lack a target for this metric. If checked, we will not be able to generate truly accurate scores for this metric without at least a quarter of data, but after at least 90 data values are entered we can automatically calculate a moving target that is responsive to your city's historic performance."),
        ),
        migrations.AlterField(
            model_name='metric',
            name='target',
            field=models.FloatField(verbose_name=b'What is the target value? If this metric is historic (i.e., the above is checked), give an estimate for an average value you expect for this metric or a pre-existing historical average, and we will pick up calculations once we have enough data. (This can be changed later!)'),
        ),
    ]
